# Generated by Django 5.0.1 on 2024-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
